### ISSUE TITLE
Bad resource

### ISSUE THREAD

**Issue by lohek** [yahoo/fetchr#101]
Hi,

On new version, you have add this
```
if (!Fetcher.isRegistered(resource)) {
  error = fumble.http.badRequest('Invalid Fetchr Access', {
    debug: 'Bad resource ' + resource
  });
  error.source = 'fetchr';
  return next(error);
}
```
But... what's happening when i want use "todo.toggleAll" on resource name (https://github.com/yahoo/flux-examples/blob/master/todo/actions/toggleAll.js#L11, https://github.com/yahoo/flux-examples/blob/master/todo/services/todo.js#L43), it's just check resource var, when it should be
```
resource.split('.')[0]
```

After maybe i completely wrong (suddenly i do not really know what to do).

Thanks !

**Comment by Vijar** [comment]
@lohek you're right, this was a mistake. I'm working on a fix right now.

**Comment by lohek** [comment]
Nice, thanks !
