### ISSUE TITLE
params vs body for create/update?

### ISSUE THREAD

**Issue by tleunen** [yahoo/fetchr#106]
Not sure to understand the differences between the 2 for a create or update request.
Could you explain or give an example?

Thanks.

**Comment by Vijar** [comment]
`params` will be sent to the service as part of the request url, whereas `body` will be serialized and sent as the request's body.

**Comment by tleunen** [comment]
Hmm.. But why would I use both `params` and `body` for the same request when I can easily put everything in `body`?

**Comment by escalona** [comment]
@tleunen An example would be if you were making a POST request to a url with query parameters. The request payload would be passed in as `body` while the query parameters would be passed in from `params`.

**Comment by tleunen** [comment]
I understand the differences when you are making request for another service that you don't control (like Flickr), but when you're making a request to your own service (you both control client and server services), it doesn't really make sense to use both `params` and `body` then

**Comment by escalona** [comment]
The same principles still applies. Say I have a messaging app and I want to update a specific message with a given id. My fetchr service would look something like:

```
update: function (req, resource, params, body, config, callback) {
    var messageId = params.messageId;
    
    // your own service url
    var url = '/api/message/' + messageId;

    request.post({url: url, data: body}, function (err, resp) {
        // handle callback
    });
}
```

Where my I use `body` in my POST and params holds other information such as url parameters. 
While you could pass all data to the service using only `body` or `params` (they are both just objects), by having the distinction it makes the service easier to read.

**Comment by tleunen** [comment]
Make sense to have this little distinction as you said. Thanks ;-)
