### ISSUE TITLE
Better instance methods API?

### ISSUE THREAD

**Issue by gpbl** [yahoo/fetchr#108]
I get often confused by the number (and the order) of the arguments I have pass to the [instance methods](https://github.com/yahoo/fetchr/blob/master/docs/fetchr.md#instance-methods), sometimes hard to debug... so I'm here to propose a different API:

```js
// old:
read(resource, params, config, callback)

// new, where `config` is now `options`
read(resource, options)
  .params(params)  
  .end(callback)

// old:
update(resource, params, body, config, callback)

// new:
update(resource, options)
   .params(params)
   .body(body)
   .end(callback)
```

For example this code 
```js
context.service.read("photo", { id, imageSize }, { timeout: TIMEOUT },
      (err, data) => {
        context.dispatch(Actions.LOAD_PHOTO_SUCCESS, data.photo);
        done();
});
```

would become

```js
service.read("photo", { timeout: TIMEOUT })
   .params( { id, imageSize } )
   .end((err, data) => {
       context.dispatch(Actions.LOAD_PHOTO_SUCCESS, data.photo);
       done();
    });
```

or a create call:

```js
service.create("user")
    .body( { firstName, lastName })
    .end(done) 
// see how no need to pass empty params when not required 👍
```

what do you think?

**Comment by lingyan** [comment]
:+1:  That's what I had been thinking about too.  Similar to superagent API.

**Comment by escalona** [comment]
I've ran into the same issues without our codebase. A lot of time body and params will get mixed up. The solution you proposed looks good. Another approach would be to accept a resource name and an options parameter. For example:

```
service.create("user", {
    params: { id: 2 },
    body: { name: "John" },
    config: { timeout: 6000 },
    callback);
```

**Comment by redonkulus** [comment]
I like @gpbl suggestions as it makes it cleaner to add configuration to the request and easier  to read.

Would be interesting if we could make this backwards compatible.

**Comment by gpbl** [comment]
🍻 it should be easy to maintain the old signature, I think something like:

```js
function create(name, options) {
  if (arguments.length > 2) {
     // API is: create(name, params, config, callback)
     let params = arguments[1];
     let config = arguments[2];
     let callback = arguments[3];
     return create(name, config)
        .params(params)
        .end(callback);
  }
  return new Fetcher(name, options);
}

class Fetcher {
  constructor(name, options) {
    this.name = name;
    this.options = options;
  }

  params(params) {
    this.params = params;
    return this;
  }

  body(body) {
    this.body = body;
    return this;
  }

  end(done) {
    // do things as now
  }
}

```

**Comment by koulmomo** [comment]
@redonkulus @gpbl make sure to warn about deprecation and then completely deprecate in the next major release.

I hate `arguments.length` checks

**Comment by escalona** [comment]
@gpbl Since config if optional you would also have to check if `typeof config === 'function'` and handle it accordingly.

**Comment by Vijar** [comment]
@koulmomo is there a perf reason for not wanting to check arguments.length or just personal preference?

**Comment by Vijar** [comment]
I really like [superagent](https://github.com/visionmedia/superagent)'s interface and everyone else who has used it seems to like it too.

I would like the API to be something like this:

```js
Fetcher
    .read('resourceName') // required
    .params({}) // optional
    .body({}) //optional
    .config({}) // optional
    .end(function(err, data){ // required
        // handle err/data
    });
```

This would be fairly easy to maintain backwards compatibility with. I can do a PR if you want. Thoughts?

**Comment by gpbl** [comment]
Ah thanks @escalona I forgot `config` was optional.
@Vijar I tend to view `config` as `options` object to pass to `create`, i.e. i find better passing it as second arguments, but i guess it's just taste :-)

**Comment by koulmomo** [comment]
@Vijar yes: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments  (though not if you implement it carefully) and personally it always looks gnarly.

**Comment by Vijar** [comment]
@koulmomo That doc mentions reading `arguments.length` isn't a performance hit, but passing it around would be though.

**Comment by Vijar** [comment]
@gpbl I can see your point. I think this comes down to one of two styles:

Option 1 (suggested by @escalona):
This is typical node style. Might be a little harder to maintain backwards compatibility
```js
service.create('user', {
    params: { id: 2 },
    body: { name: 'John' },
    config: { timeout: 6000 }
    },
    callback);
```
OR
Option 2 (superagent style):
```js
service
    .create('user') // required
    .params({ id: 2 }) // optional
    .body({ name: 'John' }) //optional
    .config({ timeout: 6000 }) // optional
    .end(callback); // required
```

I think it should be one or the other. We shouldn't mix and match.

**Comment by redonkulus** [comment]
Option 2 :+1:

**Comment by escalona** [comment]
I'm in favor of option 2 as well.

**Comment by gpbl** [comment]
👌 great then, and thanks for the positive feedback!
