### ISSUE TITLE
Response headers on client

### ISSUE THREAD

**Issue by nathanwelch** [yahoo/fetchr#109]
It's occasionally useful to have access to the response headers when handling a request (e.g. for pagination when using APIs that put totals and next/prev data in the headers rather than the response body). It doesn't seem like this is currently possible on the client because of https://github.com/yahoo/fetchr/blob/master/libs/fetcher.client.js#L369. 

Any thoughts on passing `response.headers` (or a meta object with a headers key similar to what the server supports from custom fetchers) as the 3rd argument here? Or, is there some other way to get around this that I'm not seeing?

Thanks!

**Comment by redonkulus** [comment]
:+1: to the third argument. We already do that for the server side, makes sense to do it on the client too. Want to PR it?

**Comment by redonkulus** [comment]
@pablopalacios potentially something we could add in 1.x

**Comment by pablopalacios** [comment]
@redonkulus isn't this already implemented? Since the link is targeting master, it's hard to see what @nathanwelch was facing.

But, if a operation in the server calls the callback with a `meta` object with headers, the response itself will have the headers and the response body will include the meta object with them as well. The client doesn't do anything with the `meta` object so them will be available as 3rd param in the callback or as `meta` property in the promise.

**Comment by redonkulus** [comment]
It would be worth testing out to ensure it is supported.

**Comment by pablopalacios** [comment]
And here is a test: https://github.com/yahoo/fetchr/pull/283/files#diff-810ef617329ca8501025734bc7fca09f8fe45849f568b74204cd2553960615beR262-R279

So all headers set in the meta object will be available in the client side thought the meta object as well.

**Comment by redonkulus** [comment]
Ok thanks for confirming!

**Comment by lingyan** [comment]
Speaking of meta, @snyamathi has seen problems with [passing 3 arguments to a callback function](https://github.com/yahoo/fetchr/pull/283/files#diff-bf2bfe3c8ca334e32d83b2780e098d73a61459d60fcecc39386f4a088c38a5b1R11-R15), which is not very conventional, and causes quirks with response shapes like working with [async.auto](https://caolan.github.io/async/v3/docs.html#auto) 

If we are bumping fetchr major version, maybe that can be addressed too.
