### ISSUE TITLE
promise support

### ISSUE THREAD

**Issue by benmonro** [yahoo/fetchr#111]
Just curious if there will be support for promises in the plugin and/or why they were left out?  Was this an intentional decision?  For example in reading from a service:

``` 
context.service.read("message", {}, {}).then().catch() 

```

instead of 

```
context.service.read('message', {}, {}, function (err, messages) {});
```

**Comment by mridgway** [comment]
I think its reasonable to support promises now that Fluxible does. :+1:

**Comment by KATT** [comment]
+1

**Comment by Vijar** [comment]
We can easily support this after #110 is reviewed and merged.

**Comment by samkelleher** [comment]
In my testing, the actual service still receives a callback parameter as the last argument, even if you return a promise, without calling the callback, the request is never terminated.

For example, in my action, I can write:
```
context.service.read('example', {my: 'params'}, {my: 'options'}).then(...).catch(...)
```

But the service cannot have, I'm forced to use a callback again.:
```
{
 name: 'example',
 read: function(req, resource, params, config) {
  return new Promise(...);
 }
}
```

So it looks like Promise support is only available where the service is called, but not where it is executed.

**Comment by Vijar** [comment]
@samkelleher you're right, right now promise support is only for calling services.
