### ISSUE TITLE
how can i set a timespan to xhrContext

### ISSUE THREAD

**Issue by navy235** [yahoo/fetchr#117]
how can i set a timespan to xhrContext?

**Comment by Vijar** [comment]
@navy235 are you talking about timeouts? https://github.com/yahoo/fetchr#xhr-timeouts

**Comment by navy235** [comment]
@Vijar thanks for your response,I want add a random parameter on every api  url .
Later i find out it can use clientConfig.constructGetUri  to customize the api url.
