### ISSUE TITLE
Numeric value is cast to the number when `parseParamValues` in middleware

### ISSUE THREAD

**Issue by ahomu** [yahoo/fetchr#119]
My problem is the numeric value is cast to the number would be.
It is occurring in GET request when the parsing by the middleware.

for example... http://example.com/fetchr/Example;id_str=9007199254740992000000

```javascript
function read(req, src, params, options, callback) {
  console.log(params.id_str); // => 9.007199254740992e+21
}
```

What a better solution?
thanks

**Comment by Vijar** [comment]
@ahomu Yes, this is unfortunate.

I think what we have now with converting numeric values to numbers is a sensible default. If you really want to convert numbers to strings you can easily do that by:
```
var idStr = params.id_str + '';
```

However, this only solves part of your problem. 

Fetchr middleware uses `JSON.parse` to cast numeric values to numbers but it introduces rounding errors as well as scientific notation for larger numbers. which makes the fix I suggested unusable.

So I will have a PR to fix this soon.

**Comment by ahomu** [comment]
Thank you! Look forward to the PR.

**Comment by Vijar** [comment]
@ahomu The fix should be released now.

**Comment by ahomu** [comment]
@Vijar Great! I will try it.
