### ISSUE TITLE
can you provide an example with data services or routes requiring authentication or authorization?

### ISSUE THREAD

**Issue by mypark** [yahoo/fetchr#128]
An example for say a logged in user's profile or "my account" settings would be useful, maybe with a bearer token strategy.  I would imagine you can check for a req.header in server/fetchers/flickr.js implementation, but how would you configure the client to send that token in the header on the client?  Should that be done in the client/app.js or in the shared getFlickerPhotos.js?  I suppose a shared session cookie example would be easier?

**Comment by Vijar** [comment]
@mypark this is a good idea. I'll look into adding a clear example inside flux-examples.

Meanwhile have you looked into something like `passport.js` which supports user authentication and session support. I believe it will populate `req.user` automatically from a cookie. There should be minimal work needed to protect the entire fetchr endpoint.

**Comment by mypark** [comment]
yeah I was looking at passport.js, but was unsure how to adapt the express server side implmentation to flux and fluxible.  For example - should I just use the included login http post endpoints from passport and somehow wrap that into fetchr.. or use some sort of middleware?

**Comment by koulmomo** [comment]
@mypark the common approach is to use a middleware. That way your `fetchr` services (that always run on the server) can just check `req.user` to see if it got populated in your data service methods.

so something like:
```js
const fumble = require('fumble');
const FooFetcher = {
    read (req, resource, params, config, callback) {
        if (!req.user) {
            return callback(fumble.http.unauthorized());
        }

        // continue fetching foos
    }
};
```

example fetchers can be found [here](https://github.com/yahoo/fetchr/blob/2060f317797836e40a9c84ccac7294eb8449d5dc/examples/simple/server/fetchers/flickr.js#L14) and [here](https://github.com/yahoo/flux-examples/blob/2c13e652db2ff43ab8b34539a81f63178b33e61c/chat/services/message.js#L69)

the actual initial posting to login can be set up as a route independent of `fetchr`, or you can also have a `LoginFetchr` that exposes an endpoint to login.

**Comment by mypark** [comment]
should I do something like this in the user fetchr module?

```
module.exports = {
    name: 'user',
    read: async function(req, resource, params, config, callback) {
        const username = params.username;
        if (!username) {
            return callback('username is required', null);
        }
        try {
            if (resource === 'user.login') {
                const password = params.password;
                if (!password) {
                    return callback(fumble.http.badRequest('password is required'), null);
                } else {
                    
                    passport.authenticate('local', function(err, user, info) {
                        console.log('passport local result' + err);
                        console.log('password user' + user);
                        if (user) {
                            req.session.currentUser = user;
                            return callback(null, {user: user});
                        } else {
                            return callback(fumble.http.unauthorized('invalid password or username'), null);
                        }
                        callback(err, {user: user});
                    });


                }
            }
        }
    }
}
```

**Comment by mypark** [comment]
Just tried the above example and it seems to have trouble with passport.authenticate - the function passport.authenticate('local', function(err, user, info) ... doesn't seem to be running correctly.  Is it because it's expecting a bunch of things in the closure from express?  The function seems to run fine if used like in the passport examples directly in an express route.

**Comment by Vijar** [comment]
@mypark 

I would NOT use fetchr for authenticating your users.You should use the endpoints provided by passportjs.

I'm not sure if this helps you but, here is a more detailed guide I wrote as I read the passportjs docs (I personally haven't used it yet):

1. Tell passportjs how to authenticate users (e.g. select `local` strategy)
    - Follow [Username & Password section](http://passportjs.org/docs/username-password) of the passportjs docs. Specifically make sure you do `passport.use` part.
1. Setup form and route to authenticate users
    - Setup [form](http://passportjs.org/docs#form) which points to `/login`
    - Setup the `/login` [route](http://passportjs.org/docs#route)
1. Add authentication middleware to prevent fetchr access without login
    - `app.use('/myCustomAPIEndpoint', passport.authenticate('local'), Fetcher.middleware());`
which will prevent express from calling your resources if the user isn't authenticated.

This method can be used to redirect users to your login page if they try to access fetchr without logging in.

Now, this works if you're building an application where fetchr is only used behind a login-wall, but if you want to only restrict certain resources then that is a more complicated problem. Do you have that use case?

**Comment by mypark** [comment]
Yeah I have a more mixed case where some fetchr services are public and some are restricted... e.g. search vs myAccount.  I'm using fetchr with fluxible and trying to keep it isomorphic.  Using passportjs seems like it might be a bit more trouble than its worth since its so dependent on the request routing of express.  I'm thinking it would just be easier to set up my own authentication services in the end.

**Comment by Vijar** [comment]
@mypark you can go either way but it is probably a lot easier to use passportjs. Internally, we follow the same passportjs pattern where if a user is logged in `req.user` object is available, if not `req.user` is empty. We use cookies/session to know which user is logged in, also like passportjs. 

Using middleware to authenticate is necessary imo.

If you still want to use fetchr for authentication, you technically can. You can have a fetchr data service that will return whatever is in the req.user object returned by passportjs (even if empty for non-logged in users). This way you can access this user loggedin/loggedout state from both server and client via fetchr.

In your individual "protected" data services you can simply do a `if(req.user)` checks.

This all assumes you do `app.use('/myCustomAPIEndpoint', passport.authenticate('local'), Fetcher.middleware());` with the redirect option set to false. This way fetchr is still accessible regardless of user login state. You can then granularly control what happens in each data service.

**Comment by mypark** [comment]
Do you have an example or sample code somewhere implementing this with fluxible?  Maybe that'll make it more concrete in my mind.  If we were to use the passportjs login endpoints and just POST to them from a form, that would cause a page refresh right?  Would you also try to store currentlyLogged in user in a userStore as well?  Looks like dockunit example uses passport: https://github.com/dockunit/platform .  Would you recommend this approach in their example?

The part that is confusing to me is mixing the fluxible routing and endpoints with the ismorphic routing of fluxible.  I suppose it doesn't strictly have to be all under the fluxible router.  Is your su

I'm not tied to fetchr for authoriziation so just looking for the easiest most standard way of doing things.

**Comment by koulmomo** [comment]
@mypark haven't vetted the solution personally, but I found this issue against fluxible https://github.com/yahoo/fluxible/issues/200

**Comment by Vijar** [comment]
@mypark I would start with the dockunit approach.

Especially, see here: https://github.com/dockunit/platform/blob/ca7f2c953935481b35c6a249ffbeef1326c77498/services/github.js#L8-L13

Unfortunately, I don't have an example ready at the moment, but I do want to add it when I get some downtime.
