### ISSUE TITLE
Does fetchr support non-CRUD function names?

### ISSUE THREAD

**Issue by mypark** [yahoo/fetchr#129]
I'd like to create some services that do things like "search" or "login" that doesn't necessarily fit strictly into a CRUD paradigm.

Does fetchr support naming functions that are not CRUD?

specifically in fluxible-fetchr-plugin can I do this:

`context.service.search('product', {text:keyword}, {}, callback);`

instead of this:

`context.service.read('product', {text:keyword}, {}, callback);`

Or should I just pass in a discriminator function in the params like so

`{ operation:'search', text:keyword }`

**Comment by mridgway** [comment]
Fetchr does not currently support non-CRUD methods, but you can pass "sub-resources": `context.service.read('product.search', {text:keyword}, {}, callback);`. The sub-resource would then be passed to your `resource` parameter within your `produect` service: 

```js
//...
read: function(req, resource, params, config, callback) {
    if (resource === 'product.search') { ... } 
//...
```

**Comment by figalex** [comment]
Are you guys thinking about adding this feature in the future?

**Comment by mridgway** [comment]
We don't have plans for this right now. The current CRUD operations directly map to RESTful methods, so adding more verbs may cause confusion.
