### ISSUE TITLE
Explicitly State Support

### ISSUE THREAD

**Issue by localnerve** [yahoo/fetchr#136]
I was just about to PR with the lodash 4 update, but then I realized you might be supporting IE8 with this.
Can you please explicitly state the intended support targets of the client and server side parts of this library? Maybe I missed it? Thanks.

**Comment by Vijar** [comment]
@localnerve We don't really need to support IE8 with fetchr, we were planning to upgrade lodash but it will take us a while to upgrade all the packages internally...anyway, you can just create a PR and we can do a major bump so it doesn't break anyone expecting IE8 support. 

/cc @mridgway @redonkulus

**Comment by localnerve** [comment]
OK. Can we update the travis node matrix too? What's the up-to-date intent there?

**Comment by redonkulus** [comment]
fetchr is on lodash 4 now, this can be closed.
