### ISSUE TITLE
Is there a way to proxy /api/*

### ISSUE THREAD

**Issue by mwelche** [yahoo/fetchr#139]
I have the default setup:
```
const fetcher = new Fetchr({
  xhrPath: '/api',
  xhrTimeout: 30000,
});
```
and noticed that all of my POST's have the path `/api` in the request URL regardless of the service. The referral URL is correct but my server is expecting something like `api/login` from the request URL. Is it possible to proxy similar to https://github.com/erikras/react-redux-universal-hot-example#explanation where the path can be `api/*`?

**Comment by Vijar** [comment]
@mwelche are you using your own api or are you using fetchr on the server?
