### ISSUE TITLE
Output in Error objects

### ISSUE THREAD

**Issue by gpbl** [yahoo/fetchr#141]
To handle errors I'm adding `output` to the Error object, and then pass it to the service's callback:

```js
create(req, resource, params, config, callback) {
    const err = new Error('bad');
    err.output = 'Hi there, I\'m an error!';
    callback(err);
}
```

On the client I receive the output in the `body` property of the error. I was expecting an `output` property here:

```js
// call service client-side...
fetchr.read('myService').end(err => 
    console.log(err.output);  // undefined    
    console.log(err.body);  // Hi there, I'm an error!
);
```

On the server I receive instead the output in the `output` property:

```js
// calling the the same service server-side
fetchr.read('myService').end(err => 
    console.log(err.body);  // undefined
    console.log(err.output);  // Hi there, I'm an error!
);
```

Why this difference between `err.body` and `err.output`? Since I've to call the service both server and client side, this is how I do now:

```js
fetchr.read('myService').end(err => 
    console.log(err.body || err.output); // Hi there, I'm an error!
);
```

Not sure if i'm doing it right or I'm missing something. E.g. why has been chosen `output` and not `body` as property name?

**Comment by redonkulus** [comment]
Thanks for the bug, @Vijar please take a look when you get a chance.

**Comment by gpbl** [comment]
thanks!
