### ISSUE TITLE
Cors withCredentials not passed from config in http-client

### ISSUE THREAD

**Issue by activist** [yahoo/fetchr#147]
Is it by intent that withCredentials is not passed in option from the mergeConfig function in http.client? Seems that it is not passed along, or is it perhaps a way around it?

**Comment by mridgway** [comment]
Hi @activist. Looks like we do not allow that option currently, but we should definitely add it. If you'd like to do a PR to allow this it should be relatively simple. I think we just need to add an `options.withCredentials` that gets passed in here: https://github.com/yahoo/fetchr/blob/master/libs/util/http.client.js#L172. The xhr library should then use this option (https://github.com/Raynos/xhr/blob/master/index.js#L177).

**Comment by activist** [comment]
Added pull request https://github.com/yahoo/fetchr/pull/149#issuecomment-229332312

Let me know if you have any questions.

**Comment by mridgway** [comment]
Resolved in #149.
