### ISSUE TITLE
supporting synchronous xhr requests?

### ISSUE THREAD

**Issue by mdressman** [yahoo/fetchr#164]
The underlying xhr package used by fetcher.client.js supports configuring particular requests to be synchronous, however the fetchr api does not expose this option.

I have a unique use case where I need an xhr request to be sync (window.onbeforeunload) and I really don't want to construct my own XMLHttpRequest w/ sync: true calling our fetchrXhrPath.

Is there any interest in making this a configurable fetchr option?  If so, I can take a stab at a PR. Thanks

**Comment by redonkulus** [comment]
@mdressman makes sense. Feel free to open a PR. Would we want the same functionality for the server? In most cases no, but maybe there is a use case there too.

**Comment by redonkulus** [comment]
We are removing the xhr dependency so this will not be an option in the future.
