### ISSUE TITLE
Provide more info on errors

### ISSUE THREAD

**Issue by gilligan** [yahoo/fetchr#180]
In our app we are currently experiencing some regular errors where we aren't certain about the origin. Sadly the stacktrace from fetchr isn't helping:

```
HttpError: Invalid Fetchr Access
    at create (/nix/store/ic4fdwwfi6x7mkd1b3cig194f9s768nk-hc-web-node-modules-prod/node_modules/fumble/libs/fumble.http.js:11:12)
    at Object.createMethod [as badRequest] (/nix/store/ic4fdwwfi6x7mkd1b3cig194f9s768nk-hc-web-node-modules-prod/node_modules/fumble/libs/fumble.http.js:16:16)
    at /nix/store/ic4fdwwfi6x7mkd1b3cig194f9s768nk-hc-web-node-modules-prod/node_modules/fetchr/libs/fetcher.js:362:37
[...]
```

Looking at [fetchr.js:362`](https://github.com/yahoo/fetchr/blob/608b0591b49e048b4971d886030d6e5350482e05/libs/fetcher.js#L362):

```js
            if (!Fetcher.isRegistered(resource)) {
                error = fumble.http.badRequest('Invalid Fetchr Access', {
                    debug: 'Bad resource ' + sanitizeResourceName(resource)
                });
                error.source = 'fetchr';
                return next(error);
            }
```

So the `sanitizeResourceName(resource)` is what I think should definitely be displayed in the stacktrace above. Otherwise the information you retrieve is basically: "Something went wrong because of the resource i was trying to operate on - but i won't tell you which resource that was"

Any chance that this could be changed?

**Comment by lingyan** [comment]
This is a reasonable ask.  Do you mind putting up a PR for this?

**Comment by gilligan** [comment]
@lingyan Sure, shall do- I will try to find time for it asap. Thank you for the fast feedback
