### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by Saebyuckbaan** [yahoo/fetchr#195]
Hi,
I often get setImmediate is not defined error, which is from [fetcher.client.js](https://github.com/yahoo/fetchr/blob/master/libs/fetcher.client.js).
I realized that [setImmediate](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate) is not standard function that requires polyfill.
Can we replace it with setTimeout(fn, 0), which is the equivalent standard version, or [npm package](https://www.npmjs.com/package/setimmediate?activeTab=versions)?

Testing Environment
- Chrome 82
- Firefox 68.8
- Node.js 10 and 12

**Comment by redonkulus** [comment]
@Saebyuckbaan I think thats fair. We could leverage the npm package. Do you want to PR it?

**Comment by davisyi** [comment]
Hi @redonkulus, I created a PR for requiring setImmediate polyfill for both fetchr-client and fetchr.
