### ISSUE TITLE
Fetchr 0.5.42 and IE11

### ISSUE THREAD

**Issue by matthoffner** [yahoo/fetchr#251]
Heads up we are noticing some test failures with IE11 and the recently released fetchr (0.5.42)

Error:

`Expected identifier, string or number`

Understandable that IE11 is on its way out but I wanted to surface this in case anyone else sees something similar. Ideally any change that drops IE11 support would be major, but we can pin for the time being.

**Comment by redonkulus** [comment]
Yup, we hit this internally too, we ended up just updating our babel/webpack config to transpile fetchr as well. We should have changed this in a major version.

@pablopalacios if you want to refactor your latest change to remove ES6 that would help users that haven't discovered the issue yet.

**Comment by pablopalacios** [comment]
Oh, it was really not my intention to drop support for IE11 since we also support it here. I tried to be very careful about it but it looks like some thing slipped in. I'll check it soon ;)

**Comment by redonkulus** [comment]
@matthoffner this is now fixed via https://github.com/yahoo/fetchr/pull/252, released in fetchr@0.5.43.

Thanks for the report!
