### ISSUE TITLE
Abort support, retry mechanism and promises

### ISSUE THREAD

**Issue by pablopalacios** [yahoo/fetchr#278]
@redonkulus 

**Context:** currently calling fetchr.read() with a callback [will return](https://github.com/yahoo/fetchr/blob/master/libs/util/http.client.js#L174) a `XMLHttpRequest` instance that allows us to `abort` the request if needed:

```js
const request = fetchr.read('resource', {}, {}, callback);
request.abort()
```

When we use the Promise API, this is not currently possible since we are returning a native promise. This is expected and documented since we don't implement a custom Promise interface to circumvent this issue.

**Issue:** While I was working on #271 I found another bug related to the the retry mechanism: `abort` doesn't work if the retry mechanism is triggered. The reason: [we are creating](https://github.com/yahoo/fetchr/blob/master/libs/util/http.client.js#L157) new `XMLHttpRequest` instances inside a callback and because of that the users don't have access to them. As a consequence, the request can't be aborted anymore since the one that was returned initially was already completed.

Then comes the dilemma: should we fix the issue by removing the abort feature or by really fixing it? If we kill it, it will make the job of converting everything to promises easier since we wouldn't have to create a custom promise interface that would allow us to abort it. In the other hand, `abort` seems to be a cool feature to have... We could also add it later if, for example, we replace xhr with `fetch` which would allow us to use the same `AbortController` for all requests that are triggered...

What do you say?

**Comment by redonkulus** [comment]
I would prefer to migrate to native `fetch`, removing `xhr` and then using `AbortController`, since its a standard API.

**Comment by pablopalacios** [comment]
#290 solved this issue.
