### ISSUE TITLE
Consistent unit test timeout failures

### ISSUE THREAD

**Issue by redonkulus** [yahoo/fetchr#298]
@pablopalacios I seem to be getting consistent functional test timeout failures when running locally:

```
npm ERR!   1) client/server integration
npm ERR!        "before all" hook: setupBrowser in "client/server integration":
npm ERR!      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/foo/Dev/github/fetchr/tests/functional/fetchr.test.js)
npm ERR!       at listOnTimeout (internal/timers.js:549:17)
npm ERR!       at processTimers (internal/timers.js:492:7)
```

When I run `npm test` I cannot reproduce it, but when I use `np` to publish a version, it runs a pre-commit hook that executes the tests and then fails with this error consistently. I'm not sure why test results would change from the execution paths above. 

Can you reproduce this?

**Comment by pablopalacios** [comment]
@redonkulus Hmmm, I don't know what `np` is and I don't have this hook here. But from the error message I would say that the pre-commit hook is using a different `node_modules` that does not include chromium. Thus, it can't setup the browser and the `before` mocha hook will fail. Does it make sense?

**Comment by redonkulus** [comment]
I guess so, I can try wiping node_modules and see if that helps. I dont even have a pre-commit hook installed, it could be npm publish running `npm test` automatically before publishing.

np is just a utility that makes npm releases easier, it will run tests, generate github release notes etc.

**Comment by pablopalacios** [comment]
If it's a path issue and it's a hassle on your side to figure it out, you can try setting `PUPPETEER_EXECUTABLE_PATH` env var to point to a chromium installation before running your commands. 

If after that you still get a timeout, I would just assume that things just run slower during this hook execution. Said that, I would try to increase mocha timeout. Inside the `function setupServer`, just call `this.timeout(5000)` or, in the `package.json`, add a `-t 5000` in the `test:functional`

**Comment by redonkulus** [comment]
Ok sounds good, will take a look locally. Thanks!

**Comment by pablopalacios** [comment]
Also, just make sure that you don't have `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env var set. I have this on my `bashrc` and I always spend hours debugging why puppeteer is not working when I run functional tests locally.

**Comment by redonkulus** [comment]
Thanks for the tips, increasing the timeout helped. I also removed the pre-commit package which wasn't necessary.
