### ISSUE TITLE
Create / Read / Update / Delete

### ISSUE THREAD

**Issue by ptomasroos** [yahoo/fetchr#33]
Why are the fetching using CRUD naming instead of just using the verbs of HTTP?

Post / Get / Put / Delete, 

The problem I see it that many are already existing and this one is forcing ppl to align their api's just to be able to use the technology.

I would rather have fetcher.post('discover', 'markItemAsClicked'

Today all the fetcher are boxed in to only have read: create: update: delete: on the server which i think is pretty limiting.

Whats your thought on this? Wouldnt it be good to have any named server side resources rather than being limited to CRUD.

**Comment by BerkeleyTrue** [comment]
Seems like batching has been implemented. Should this issue be closed now?

**Comment by Vijar** [comment]
@BerkeleyTrue Actually, the batching code is very old and I'm pretty sure it doesn't really work.

We discussed implementing batching recently. Given that `fetchr` is primarily used with React and the impending release of [Relay](https://facebook.github.io/react/blog/2015/02/20/introducing-relay-and-graphql.html)(potentially in 2 weeks at [React Europe](https://www.react-europe.org/#relay-anchor)), we don't think it is the best idea to prioritize batching at this point.
