### ISSUE TITLE
Rename services' 'name' property to 'resource'

### ISSUE THREAD

**Issue by Vijar** [yahoo/fetchr#51]
It makes more sense that way

**Comment by escalona** [comment]
@Vijar Is this still something that needs to be updated? I can create a PR if so.

**Comment by redonkulus** [comment]
@escalona  its a nice to have, we could probably make it backwards compatible so we do not break existing services. You can PR it if you like.

**Comment by pablopalacios** [comment]
@redonkulus I'll probably take this one as well.

**Comment by redonkulus** [comment]
Sounds good, lets make it backwards compatible to avoid a breaking change.
