### ISSUE TITLE
coerce 'undefined' string to undefined

### ISSUE THREAD

**Issue by BerkeleyTrue** [yahoo/fetchr#55]
When a param is undefined, server side the api returns the actual undefined primitive, but on request from client the undefined param is now a string. This means for every string param we need to check whether the value is true-y and as well not equal to the string 'undefined'.

**Comment by mridgway** [comment]
Sounds like an inconvenient bug. We'll take a look at it.

**Comment by BerkeleyTrue** [comment]
Hooray!
