### ISSUE TITLE
Client-side timeouts

### ISSUE THREAD

**Issue by gpbl** [yahoo/fetchr#58]
Client-side requests often get answers after the [3 seconds timeout](https://github.com/yahoo/fetchr/blob/master/libs/util/http.client.js#L19-L21): i.e. mobile users with bad connections or requests to external services.

It would be useful being able to set the timeout globally, instead of passing it as config to each service. For example, I'd put it to 30s, after which it seems reasonable to show an error. The default is imho too short.

What do you think?

**Comment by koulmomo** [comment]
I like the idea of being able to change the default configs all at once, but I think the default should still be 3 seconds.

I might be wrong, but I *feel* that in most cases (especially in development) it would be helpful to identify which of your services are slow so that you can either fine tune them, or adjust timeouts for those specific services.

**Comment by gpbl** [comment]
@koulmomo does the timeout affect users with slow connections? I have reports of users connecting from mobile. I've also seen it on my computer when it was heavy downloading stuff. In this case the problem is not the service, but the client – hence my need to set the timeout for *all* the service calls.

**Comment by koulmomo** [comment]
@gpbl I'm saying that you **SHOULD** be able to change the defaults for services **ALL AT ONCE**, but if the developer does not choose to do so, it should still default to 3s.

```js
// illustrating a point, not the proposed api
var fetcher = require('fetchr'); // fetcher defaults to 3s timeout
fetcher.defaults({
    timeout: 30 * 1000
}); // fetcher defaults to 30s timeouts
```

**Comment by geekyme** [comment]
@koulmomo I think that @gpbl is right about the 3s default. It does not appear to make sense. And before I stumbled onto this thread, I didn't know about the 3s and spent a few hours debugging this. I build web apps for mobile access and these networks are often unpredictable to the point that 3s timeouts would not be sufficient.

**Comment by redonkulus** [comment]
Fixed by https://github.com/yahoo/fetchr/pull/107
