### ISSUE TITLE
Possible to remove "resource" keyword or make it configurable?

### ISSUE THREAD

**Issue by lenage** [yahoo/fetchr#64]
I have an API endpoint which look like "/api/v1/session", and i want to use fetchr to get data from server.

here is my setup:

``` javascript
app.plug(fetchrPlugin({
    xhrPath: '/api/v1'
}));
```

but when i checked out the request, it added a `resource` in URL, and it defined in: [fetcher.client.js#L294](https://github.com/yahoo/fetchr/blob/master/libs/fetcher.client.js#L294),

so, i think it would be good to make that keyword configurable?

**Comment by Vijar** [comment]
Hmm,  yeah there seem to be other issues with the "resource" prefix. I think making it configurable is fine. 

Although,  I think we might even be able to remove it completely. That would be a breaking change. Let me think of the use cases where "resource" might be needed and get back to this

**Comment by Vijar** [comment]
Resolved by #69
