### ISSUE TITLE
Xhr file uploads

### ISSUE THREAD

**Issue by growlsworth** [yahoo/fetchr#72]
Hey yahoo,

Thanks for this great library. I've looked around the source a while and cannot figure out how I would begin to support ajax file uploads. Does fluxible support xhr file uploads?

Thanks!

**Comment by Vijar** [comment]
@growlsworth 

Fetcher is supposed to be used for when you need to work with your data on both server/client and want to use the same syntax on the server/client.

However, an xhr file upload is always going to be initiated client side so it doesn't necessarily make sense as a feature that fetchr would support.

**Comment by growlsworth** [comment]
Hey thanks for the response @Vijar. 

Fetchr also handles `create` and `update` methods which would be also be created from a client.

The reason fetchr does not support file uploads is that fetchr forces empty headers on create (https://github.com/yahoo/fetchr/blob/master/libs/fetcher.client.js#L421, sent to: (https://github.com/yahoo/fetchr/blob/master/libs/util/http.client.js#L246). It also does not return the [request object](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) to add [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData).

I'm happy to submit a pull request if fetchr would consider supporting xhr file uploads either in a nice api, or via greater configuration by returning lower level objects.
