### ISSUE TITLE
Add X-Requested-With: XMLHttpRequest header

### ISSUE THREAD

**Issue by lingyan** [yahoo/fetchr#83]
It is a common header used for identify Ajax requests: http://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields

**Comment by Vijar** [comment]
Fixed by #84

**Comment by neilius** [comment]
What are your thoughts on disabling (or allowing a configuration value that disables) the X-Requested-With header for CORS-based implementations? When performing CORS requests, the X-Requested-With forces a pre-flight OPTIONS request that would be nice to eliminate. jQuery, for example, [is structured this way](https://github.com/jquery/jquery/blob/master/src/ajax/xhr.js#L60)

**Comment by lingyan** [comment]
@neilius That sounds good.  We can turn off X-Requested-With header for cross domain requests.  Do you want to file a PR?  :)

**Comment by neilius** [comment]
Yeah, certainly

**Comment by lingyan** [comment]
Thanks!
