### ISSUE TITLE
Remove `config` param from service

### ISSUE THREAD

**Issue by Vijar** [yahoo/fetchr#87]
Right now `config` does not work the same on client and server. On the client it controls things like xhr timeouts and is never serialized and sent to the fetchr middleware, on the server it is just data that is passed into the service.

This is inconsistent. We can assume not many people use it because it took so long to find. Since config has been optional for a while now, we should just remove it and bump minor.

@redonkulus  @lingyan

**Comment by redonkulus** [comment]
what are the changes to the interface? how does this affect users? are we just combining params and configs? if xhr is still used on the client, how does that get used in the new API?

**Comment by escalona** [comment]
I've run into problems with this when calling a service from the client where I'm expecting config to be defined.

Instead of removing the config object, could it simply be renamed in fetcher.client to xhrConfig with updated docs to reflect the difference?

**Comment by Vijar** [comment]
@escalona I'm leaning towards this approach too.

**Comment by escalona** [comment]
@Vijar I've created a PR with an updated config name as well as additional docs. Decided to use the name "clientConfig" as it appears that object is responsible for more than just XHR config options.

I'd like to document the other options as well but need more insight into a few of them. Will create a separate issue to track.

**Comment by Vijar** [comment]
Fixed by #92
