### ISSUE TITLE
Provide koa middleware

### ISSUE THREAD

**Issue by dlindenkreuz** [yahoo/fetchr#89]
Current middleware is not compatible with koa because the `ctx.req` and `ctx.res` objects are handled differently in Express / Connect.

**Comment by dlindenkreuz** [comment]
Maybe provide a more generic solution that processes the native Node `req` and `res` objects, then returns a generic response object containing status code, body and type (Promises?).

Middleware for app frameworks would then use the more generic version and map the response object's properties to their own response object.

**Comment by Vijar** [comment]
@dlindenkreuz I'm looking into how we can refactor the middleware to make it more extensible.

**Comment by dlindenkreuz** [comment]
I cooked up some middleware that works with koa and fetchr v0.5.14. Use at your own risk.

https://gist.github.com/dlindenkreuz/9ae51ff36421ca13cad3
