### ISSUE TITLE
Fetcher client not handling error properly

### ISSUE THREAD

**Issue by davidhouweling** [yahoo/fetchr#90]
Recently a change was made so that the errors are now being sent as a JSON object instead of a pure string https://github.com/yahoo/fetchr/commit/deef81c24055094ac225848f03898dd04b4abd1c. However, this change has not been reflected properly in the fetcher client and is still expecting it as a string.

The actual result of this [for the callback method] is that the error parameter is now an error object (which is the same as before i believe), with the message property being the JSON string that got sent from the server rather than just the message string itself.

If the intention was to make it that anyone from the server side could pass more than just a message, then perhaps the response parameter should be a parsed JSON object instead of being undefined?

In regards to where the work should be done,  I'm not sure if it's more appropriate to update the http client instead to cover all errors in one go, or if it should be parsed in each of the REST methods inside fetcher client.

I could look at making the changes, but what was the original intent of the commit that caused this issue?

**Comment by Vijar** [comment]
@davidhouweling The original intent was just to return a JSON parseable error object for some of our caching logic. Are you noticing that the client has the stringified json as the error message? It would be a good idea to add a test for this.

Now that the middleware always returns JSON, it seems like a good idea to parse the JSON in `http.client` somewhere in this [if block](https://github.com/yahoo/fetchr/blob/master/libs/util/http.client.js#L190) then set the message property on the error object correctly.

We would welcome a PR!

**Comment by lukemadera** [comment]
@Vijar Agreed on keeping the API consistent as JSON, though any reason the error data is stripped out? I opened a separate issue here: #97
